# Maquina 1 -> Ubuntu
# Actualizar repositiors de software
# Instalacion de nginx
# Instalacion de curl
# Instalacion de git

# Configurar NGINX
# GENERAR un fichero de configuración <- CONMIGO
# CARGAR UNA WEB DE UN GIT <- CONMIGO

# Arrancar el """servicio""" de nginx
# INICIAR EL NGINX

# Comprobación
# Revisar el puerto: 80
# Comprobación de que el servidor devuelve contenido: COHERENTE!!!!


- hosts: 172.17.0.2
  remote_user: root
  vars:
    # Variable simple
    nginx_port: 80
    nginx_to_test: NGINX
    
  tasks:
    - name: Actualizar repositiors
      apt: update_cache=yes
    
    - name: Install nginx
      apt: name=nginx state=present
      
    - name: Install curl
      apt: name=curl state=present
      
    - name: Install git
      apt: name=git state=present
      
    - name: Install ufw
      apt: name=ufw state=present
      
    - name: Asegurar nginx esta parado
      service: name=nginx state=stopped
      
    - name: Actualizar nginx
      apt: name=nginx state=latest
      tags:
        - actualizar
        - nginx
      
    - name: Actualizar curl
      apt: name=curl state=latest
      tags:
        - actualizar
        - curl
      
    - name: Actualizar git
      apt: name=git state=latest
      tags:
        - actualizar
        - git
        
    - name: Asegurar nginx arrancado
      service: name=nginx state=started
      notify:
        - Abrir puerto 80
        - Comprobar el puerto
        - Comprobar el contenio de nginx
      



  handlers:
    # Abrir el puerto 80
      - name: Abrir puerto 80
        ufw:
          rule: allow
          port: "{{ nginx_port }}"
          proto: tcp

    
      - name: Comprobar el contenio de nginx
        uri:
          url: "http://{{ansible_hostname}}:{{ nginx_port }}"
          return_content: yes
          status_code: 200
          timeout: 10
        register: conn
        failed_when: "'nginx' not in conn.content"
    
    
      - name: Comprobar el puerto
        wait_for:
          host: "{{ansible_hostname}}"
          port: "{{ nginx_port }}"
          delay: 5
          timeout: 10
        register: port_check
        ignore_errors: True